// Code generated by cmd/reset; DO NOT EDIT.

package model

func (v *Urls) Reset() {
	if v == nil {
		return
	}
	v.Original = ""
	v.ShortURL = ""
	v.UserID = ""
	v.Deleted = false
}

func (v *User) Reset() {
	if v == nil {
		return
	}
	v.ID = ""
	v.Urls = v.Urls[:0]
}
